### ISSUE TITLE
NHibernate.Caches.StackExchangeRedis.DistributedLocalCacheRegionStrategy UpdateTimestampsCache concurrency issue

### ISSUE THREAD

**Issue by gokhanabatay** [nhibernate/NHibernate-Caches#103]
Hi,
When we use NHibernate.Caches.StackExchangeRedis NH Second Level Cache "`DistributedLocalCacheRegionStrategy`" with one entity, performance is great.
In our scenario: 300 tables are mostly readonly, using `Cache .NonStrictReadWriteCache()`. System has also 100 more online tables that perform insert/update/delete every 1-2ms. So system always takes insert/update/delete operation in every 3-4 ms.
 
Here lies a bottleneck with `UpdateTimestampsCache`: when second level cache is enabled read operations is great only if there is no write operation at the same time. This happens even for entities/spaces which have no need to interact with the  "UpdateTimestampsCache".

Am I missing something? This issue is also raised here: nhibernate/nhibernate-core#2735.

[Third Level Cache](https://github.com/nhibernate/NHibernate-Caches/pull/72) Performance Notes by @maca88  also shows the idea of sync time increases on concurrent requests(our case 300-400 tps), so other clients waits to read/write while executing operation completes. Any cached query read with `StandardQueryCache` waits because only one writer can access `AsyncReaderWriterLock`  -> `UpdateTimeStampsCache` at the same time. Any other dml operation waits because there is only one `UpdateTimestampsCache`.

[Java Implementation](https://github.com/hibernate/hibernate-orm/blob/09cc94c4d9f9093ba990c4bdd8c660056ea9826b/hibernate-core/src/main/java/org/hibernate/cache/internal/TimestampsCacheEnabledImpl.java) have no lock.

Simple possible solution: do not interact with `UpdateTimestampsCache` if it is a non cached entity?

NHibernate:5.3.8
NHibernate.Caches.StackExchangeRedis 5.7.0

**Comment by fredericDelaporte** [comment]
All this depends on NHibernate implementation and is not actually related to caches providers, so this issue has to be handled on NHibernate side. And it has been handled on NHibernate side, see nhibernate/nhibernate-core#2744, nhibernate/nhibernate-core#2742 and nhibernate/nhibernate-core#2115.
