### ISSUE TITLE
Compatibility net core 3.1

### ISSUE THREAD

**Issue by robertovaldesperez** [nhibernate/NHibernate-Caches#105]
Package 'NHibernate.Caches.SysCache2 5.7.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.

**Comment by fredericDelaporte** [comment]
See the [documentation](https://nhibernate.info/doc/nhibernate-reference/caches.html#NHibernate.Caches.SysCache2):
> This is a .Net Framework only library, since System.Web.Caching is available neither in the .Net Standard nor in .Net Core.
