### ISSUE TITLE
Obsolete some cache providers?

### ISSUE THREAD

**Issue by hazzik** [nhibernate/NHibernate-Caches#143]
Some of the cache providers are long dead:

* SharedCache - Last [release](https://web.archive.org/web/20150810144948/http://www.sharedcache.com/cms/release_notes.aspx) was in March 2009 (15 years ago as for now). The website stopped functioning in 2015/2016. [CodePlex](https://web.archive.org/web/20210701012526/https://archive.codeplex.com/?p=sharedcache) was shut down in July 2021. Luckily Internet Archive has the archive of the codeplex site and source code. [Here](https://github.com/ronischuetz/Shared-Cache) suppose to be a copy of the source code, but the repo is empty.
* Prevalence - even older. Last [release](https://sourceforge.net/projects/bbooprevalence/files/Bamboo.Prevalence/1.4.4.4%20-%20subsystems/) in March 2005 (19 years ago). Copy of the source code is [here](https://github.com/bamboo/Bamboo.Prevalence). 
* Velocity - seems like [research project by Microsoft](https://learn.microsoft.com/en-us/archive/blogs/velocity/) that never made it to a release. It was later merged into AppFabric (using different assemblies/namespaces). Support for AppFabric [has ended in  Apr 12, 2022](https://learn.microsoft.com/en-us/lifecycle/products/appfabric-11-for-windows-server).

**Comment by fredericDelaporte** [comment]
They are already obsoleted in a way: not published as NuGet packages. Do you mean deleting them from the source? Removing them from the [documentation](https://nhibernate.info/doc/nhibernate-reference/caches.html) (only Prevalence is there)? Removing them from the binary package added on the GitHub Release?

We may include in this list the MemCache cache: it uses a very obsolete client. EnyimMemcached should be used instead.

**Comment by hazzik** [comment]
All of these? 

What I really wanted to achieve is to remove outdated binaries from the repository. Everything else is secondary.

**Comment by fredericDelaporte** [comment]
Ok.
