### ISSUE TITLE
NHibernate.Caches.CoreDistributedCache.Memcached.dll is unsigned

### ISSUE THREAD

**Issue by spasecookee** [nhibernate/NHibernate-Caches#162]
The csproj file NHibernate.Caches.CoreDistributedCache.Memcached.csproj has the following  `<SignAssembly>False</SignAssembly>`

Every other csproj file in CoreDistributedCache has `<SignAssembly>True</SignAssembly>`.

**Comment by fredericDelaporte** [comment]
It cannot.
See https://github.com/nhibernate/NHibernate-Caches/pull/29#discussion_r176908236, it has unsigned dependencies.
