### ISSUE TITLE
Add a Core RtMemoryCache

### ISSUE THREAD

**Issue by fredericDelaporte** [nhibernate/NHibernate-Caches#38]
System.Runtime.Caching is ported to .Net Core 2.1, to be released in Q2 of 2008. dotnet/corefx#14529.

So once released, RtMemoryCache could gain an netcoreapp2.1 target. (Unfortunately not a netstandard2.1, no plan for inclusion seems scheduled, dotnet/standard#682.)

**Comment by hazzik** [comment]
It will have .NET Standard 2.0 target as well. https://www.nuget.org/packages/System.Runtime.Caching
