### ISSUE TITLE
How to clear distributed cache?

### ISSUE THREAD

**Issue by danspam** [nhibernate/NHibernate-Caches#44]
It appears that using one of the CoreDistributedCache providers means that you cannot use things like `sessionFactory.EvictQueries()` to clear the cache as you just get a  warning of 'Clear is not supported by IDistributedCache'. Any thoughts on how to clear the cache when using one of these providers?

**Comment by fredericDelaporte** [comment]
That is an external issue: `IDistributedCache` just does not support the feature, nor does it support some dependency mechanism allowing to handle it (like done with `MemoryCache`). There are no ways of clearing it in its current state.

See aspnet/Caching#96.

So I do not think this will be available any time soon.

If your use cases cannot work correctly without this feature and if they use Redis, you may have better to fork [TheCloudlessSky/NHibernate.Caches.Redis](https://github.com/TheCloudlessSky/NHibernate.Caches.Redis) for upgrading it to a recent NHibernate and migrating it to .Net Core. (Simple upgrade to NH 5 is available with TheCloudlessSky/NHibernate.Caches.Redis#31, a more convoluted one attempting to support NHibernate 4 altogether (I do not really see what is the point in doing this) is TheCloudlessSky/NHibernate.Caches.Redis#33. Both are lacking the .Net Core migration.)

**Comment by fredericDelaporte** [comment]
In fact, a global `Clear` is not actually what is needed by NHibernate, because NHibernate needs to clear only regions of the cache, not the whole cache. Some dependency mechanism allowing to create a dependency between all entries of a region and a special cached item, which removal would trigger removal of all dependent entries, would allow a better clear implementation.

**Comment by danspam** [comment]
Understood. I don't need to clear the cache too often and for now I can probably do this directly on Redis. If this turns out to be insufficient I will look into the other Redis provider.
