### ISSUE TITLE
Possibility to configure Redis programmatically.

### ISSUE THREAD

**Issue by rhaikonen** [nhibernate/NHibernate-Caches#54]
We use our own configuration system instead of .config files, so it would be neat to give connection string etc. to cache provider from i.e. when building session factory.

**Comment by fredericDelaporte** [comment]
`CoreDistributedCacheProvider` has a static `CacheFactory` property, allowing to access or set the redis cache factory.
You can build it by code with the settings you wish, then affect it to `CoreDistributedCacheProvider.CacheFactory`.
This should be done before building session factories.

**Comment by rhaikonen** [comment]
Thanks!
