### ISSUE TITLE
Configure programmatically

### ISSUE THREAD

**Issue by rhaikonen** [nhibernate/NHibernate-Caches#59]
Hi, is it possible to configure that new 
NHibernate.Caches.StackExchangeRedis provider programmatically?

**Comment by fredericDelaporte** [comment]
Why would it be not possible? Have you tried? Just check what is available on the [provider class](https://github.com/nhibernate/NHibernate-Caches/blob/73b572203290887b515fc4ef9356a384a12d635b/StackExchangeRedis/NHibernate.Caches.StackExchangeRedis/RedisCacheProvider.cs#L25).

Please note by the way that here it is the issue tracker, meant for bug reports or feature requests. For support request, use the nhusers Google group.
http://groups.google.com/group/nhusers
