### ISSUE TITLE
CoreDistributedCache: BinaryFormatter key Value cannot be null

### ISSUE THREAD

**Issue by petertownsend** [nhibernate/NHibernate-Caches#76]
The `Put` method is serializing the key object. When this is a QueryCacheKey object it cannot be deserialized when starting a new instance (ie different session factory) and fails in the Get method.

This can be fixed by serializing the cacheKey instead. 

```
byte[] cachedData;
var serializer = new BinaryFormatter();
var cacheKey = GetCacheKey(key);

using (var stream = new MemoryStream())
{
	var entry = new Tuple<object, object>(cacheKey, value); // use cacheKey instead
	serializer.Serialize(stream, entry);
	cachedData = stream.ToArray();
}
```

**Comment by fredericDelaporte** [comment]
It would be missing the point of serializing the actual key with the value, and this will cause other bugs. See `GetCacheKey` comments.
https://github.com/nhibernate/NHibernate-Caches/blob/d1f41a83b36fc6ae9e3d140e92c5a2610e773988/CoreDistributedCache/NHibernate.Caches.CoreDistributedCache/CoreDistributedCache.cs#L302-L303

You should instead report the deserialization failure you witness on `QueryCacheKey`, which should be fixed, very likely on [NHibernate core](https://github.com/nhibernate/nhibernate-core) side.
Please include in this report which exception you get (full), or even better, a full test case.

**Comment by petertownsend** [comment]
Confirmed that the issue is related to naming of session factories, setting the name as per the release notes fixed the issue. Thanks.
