### ISSUE TITLE
Allow replacing ConfigurationManager for reading values

### ISSUE THREAD

**Issue by javvids** [nhibernate/NHibernate-Caches#79]
CoreMemoryCache uses `ConfigurationManager` for reading values. This doesn't work in Azure Functions V2. Can we have a custom option of providing cache values?

**Comment by fredericDelaporte** [comment]
Something like nhibernate/nhibernate-core#2116?

**Comment by fredericDelaporte** [comment]
By the way, configuration can be programmatically done, in case you have not seen.
`CoreMemoryCacheProvider` exposes some static members for this. Most cache providers do the same.

**Comment by javvids** [comment]
Thanks
