### ISSUE TITLE
Add support for custom serializer in CoreDistributedCache

### ISSUE THREAD

**Issue by zgabi** [nhibernate/NHibernate-Caches#83]
`CoreDistributesCache `is using BinaryFormatter for serializing the cache data:
https://github.com/nhibernate/NHibernate-Caches/blob/d1f41a83b36fc6ae9e3d140e92c5a2610e773988/CoreDistributedCache/NHibernate.Caches.CoreDistributedCache/CoreDistributedCache.cs#L377-L382

In .NET Core some types are not serializable anymore, for example `System.Net.IPAddress`, so it makes impossible to cache those entities which has this property type.

If I see it right there is some (or at least one) providers which already support the custom serializer:
https://github.com/nhibernate/NHibernate-Caches/blob/d1f41a83b36fc6ae9e3d140e92c5a2610e773988/StackExchangeRedis/NHibernate.Caches.StackExchangeRedis/RedisCacheConfiguration.cs#L26-L30

So I think it is relatively easy to put the same functionality to the `CoreDistributedCache` provider.

Another reason is to make the serialization faster and making smaller serialized data (for example with ProtoBuf).

**Comment by fredericDelaporte** [comment]
Or else we should at least provide a way to set `SurrogateSelector` on the binary formatter.

**Comment by zgabi** [comment]
Thank you very much @fredericDelaporte :)

Could you please give me a rough estimation when will be it released as an official nuget package?
I'm asking it because if is just some days, I'll wait for that.. otherwise I'll build my own package.

**Comment by fredericDelaporte** [comment]
I do not think it will be released in a few days.
It is more likely to be released in a few weeks.

**Comment by fredericDelaporte** [comment]
See #88, it is released.

**Comment by zgabi** [comment]
Thank you.
